from __future__ import annotations

from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


class PdfService:
    def build_report(
        self,
        overview: dict,
        recommendations: list[dict],
        action_plan: list[dict],
        swot: dict,
        reviews: dict,
        competitor: dict,
    ) -> bytes:
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
        styles = getSampleStyleSheet()
        styles.add(
            ParagraphStyle(
                name="SectionTitle",
                parent=styles["Heading2"],
                textColor=colors.HexColor("#1f2937"),
                spaceAfter=10,
            )
        )
        styles.add(
            ParagraphStyle(
                name="BodySmall",
                parent=styles["BodyText"],
                fontSize=9,
                leading=12,
            )
        )

        story: list = []
        story.append(Paragraph("AI Business Growth Assistant Report", styles["Title"]))
        story.append(Spacer(1, 0.12 * inch))
        story.append(Paragraph(f"Business: {overview['businessName']}", styles["Heading3"]))
        story.append(Paragraph(f"Website: {overview['website']}", styles["BodyText"]))
        story.append(Paragraph(f"Overall Score: {overview['overallScore']} / 100", styles["BodyText"]))
        story.append(Spacer(1, 0.18 * inch))

        story.append(Paragraph("Key Recommendations", styles["SectionTitle"]))
        story.extend(self._table_from_recommendations(recommendations, styles))
        story.append(Spacer(1, 0.18 * inch))

        story.append(Paragraph("Priority Action Plan", styles["SectionTitle"]))
        story.extend(self._table_from_action_plan(action_plan, styles))
        story.append(Spacer(1, 0.18 * inch))

        story.append(Paragraph("SWOT Summary", styles["SectionTitle"]))
        story.extend(self._table_from_swot(swot, styles))
        story.append(Spacer(1, 0.18 * inch))

        story.append(Paragraph("Review Intelligence", styles["SectionTitle"]))
        story.append(Paragraph(f"Total reviews: {reviews['totalReviews']}", styles["BodyText"]))
        story.append(
            Paragraph(
                f"Positive: {reviews['sentimentBreakdown'][0]['value']}%, Neutral: {reviews['sentimentBreakdown'][1]['value']}%, Negative: {reviews['sentimentBreakdown'][2]['value']}%",
                styles["BodyText"],
            )
        )
        story.append(Spacer(1, 0.18 * inch))

        story.append(Paragraph("Competitor Snapshot", styles["SectionTitle"]))
        story.append(Paragraph(f"Tracked competitors: {len(competitor['competitors'])}", styles["BodyText"]))
        story.append(Paragraph("This report was generated by AI Business Growth Assistant.", styles["BodySmall"]))

        doc.build(story)
        buffer.seek(0)
        return buffer.read()

    def _table_from_recommendations(self, recommendations: list[dict], styles) -> list:
        rows = [["Title", "Impact", "Effort", "Revenue"]]
        rows.extend([[item["title"], item["impact"], item["effort"], item["revenueEstimate"]] for item in recommendations])
        return self._styled_table(rows, [2.3 * inch, 0.9 * inch, 0.9 * inch, 1.5 * inch])

    def _table_from_action_plan(self, action_plan: list[dict], styles) -> list:
        rows = [["Rank", "Task", "Owner", "Due", "Score"]]
        rows.extend([[item["rank"], item["title"], item["owner"], item["due"], item["score"]] for item in action_plan])
        return self._styled_table(rows, [0.55 * inch, 2.25 * inch, 1.0 * inch, 0.85 * inch, 0.8 * inch])

    def _table_from_swot(self, swot: dict, styles) -> list:
        rows = [["Strengths", "Weaknesses", "Opportunities", "Threats"]]
        max_rows = max(len(swot["strengths"]), len(swot["weaknesses"]), len(swot["opportunities"]), len(swot["threats"]))
        for index in range(max_rows):
            rows.append(
                [
                    swot["strengths"][index] if index < len(swot["strengths"]) else "",
                    swot["weaknesses"][index] if index < len(swot["weaknesses"]) else "",
                    swot["opportunities"][index] if index < len(swot["opportunities"]) else "",
                    swot["threats"][index] if index < len(swot["threats"]) else "",
                ]
            )
        return self._styled_table(rows, [1.7 * inch, 1.7 * inch, 1.7 * inch, 1.7 * inch])

    def _styled_table(self, rows: list[list], col_widths: list[float]) -> list:
        table = Table(rows, repeatRows=1, colWidths=col_widths)
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4f46e5")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("LEADING", (0, 0), (-1, -1), 10),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.HexColor("#f8fafc")]),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        return [table]
